/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen_lab__franklin_garcia;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Franklin Garcia
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tab_principal = new javax.swing.JTabbedPane();
        panel_adiministracion = new javax.swing.JPanel();
        tab_administracion = new javax.swing.JTabbedPane();
        panel_agregar = new javax.swing.JPanel();
        tab_persona = new javax.swing.JTabbedPane();
        panel_alumno = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tf_carrera = new javax.swing.JTextField();
        panel_politico = new javax.swing.JPanel();
        cb_partido = new javax.swing.JComboBox<>();
        empleado = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tf_empleado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_edad = new javax.swing.JTextField();
        tf_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_boleto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cb_departamento = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tf_dinero = new javax.swing.JTextField();
        boton_guardar = new javax.swing.JButton();
        panel_eliminar = new javax.swing.JPanel();
        panel_reportes = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        cb_personas = new javax.swing.JComboBox();
        panel_modificar = new javax.swing.JPanel();
        tf_nuevonombre = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tab_persona1 = new javax.swing.JTabbedPane();
        panel_alumno1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        tf_carrera1 = new javax.swing.JTextField();
        panel_politico1 = new javax.swing.JPanel();
        cb_partido1 = new javax.swing.JComboBox<>();
        empleado1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        tf_empleado1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        panel_ventas = new javax.swing.JPanel();
        panel_rifas = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tab_principal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tab_principalStateChanged(evt);
            }
        });

        tab_administracion.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tab_administracionStateChanged(evt);
            }
        });

        jLabel7.setText("Carrera");

        javax.swing.GroupLayout panel_alumnoLayout = new javax.swing.GroupLayout(panel_alumno);
        panel_alumno.setLayout(panel_alumnoLayout);
        panel_alumnoLayout.setHorizontalGroup(
            panel_alumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_alumnoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(tf_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_alumnoLayout.setVerticalGroup(
            panel_alumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_alumnoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panel_alumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(345, Short.MAX_VALUE))
        );

        tab_persona.addTab("alumno", panel_alumno);

        cb_partido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nacional", "Liberal", "Pac", "Resistencia" }));

        javax.swing.GroupLayout panel_politicoLayout = new javax.swing.GroupLayout(panel_politico);
        panel_politico.setLayout(panel_politicoLayout);
        panel_politicoLayout.setHorizontalGroup(
            panel_politicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_politicoLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(cb_partido, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        panel_politicoLayout.setVerticalGroup(
            panel_politicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_politicoLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(cb_partido, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(302, Short.MAX_VALUE))
        );

        tab_persona.addTab("politico", panel_politico);

        jLabel8.setText("Ingrese su empleo");

        javax.swing.GroupLayout empleadoLayout = new javax.swing.GroupLayout(empleado);
        empleado.setLayout(empleadoLayout);
        empleadoLayout.setHorizontalGroup(
            empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empleadoLayout.createSequentialGroup()
                .addGroup(empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(empleadoLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel8))
                    .addGroup(empleadoLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(tf_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        empleadoLayout.setVerticalGroup(
            empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empleadoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(tf_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(343, Short.MAX_VALUE))
        );

        tab_persona.addTab("empleado", empleado);

        jLabel1.setText("Nombre");

        jLabel2.setText("Edad");

        tf_edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_edadActionPerformed(evt);
            }
        });

        tf_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nombreActionPerformed(evt);
            }
        });

        jLabel3.setText("ID");

        tf_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idActionPerformed(evt);
            }
        });

        jLabel4.setText("ID Boleto");

        jLabel5.setText("Departamento");

        cb_departamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "La Paz", "Francisco Morazan", "Olancho", "Intibuca", "Lempira", "Ocotepeque", "Choluteca", "Atlantida", "Cortes", "Gracias a Dios", "Copan", "El Paraiso", "Valle", "Comayagua", "Yoro", "Islas de la Bahia", "Colon", " " }));

        jLabel6.setText("Dinero");

        tf_dinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_dineroActionPerformed(evt);
            }
        });

        boton_guardar.setText("Guardar");
        boton_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_guardarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_agregarLayout = new javax.swing.GroupLayout(panel_agregar);
        panel_agregar.setLayout(panel_agregarLayout);
        panel_agregarLayout.setHorizontalGroup(
            panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_agregarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(panel_agregarLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(cb_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(boton_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_agregarLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(46, 46, 46)
                                .addComponent(tf_dinero, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panel_agregarLayout.createSequentialGroup()
                                    .addGap(74, 74, 74)
                                    .addComponent(tf_boleto, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_agregarLayout.createSequentialGroup()
                                    .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                    .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_agregarLayout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panel_agregarLayout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tf_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tab_persona, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_agregarLayout.setVerticalGroup(
            panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_agregarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_agregarLayout.createSequentialGroup()
                        .addComponent(tab_persona)
                        .addGap(24, 24, 24))
                    .addGroup(panel_agregarLayout.createSequentialGroup()
                        .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_agregarLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(tf_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)))
                        .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_agregarLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel3)
                                .addGap(33, 33, 33)
                                .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(tf_boleto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panel_agregarLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)))
                        .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cb_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(panel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tf_dinero, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addComponent(boton_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))))
        );

        tab_administracion.addTab("agregar", panel_agregar);

        javax.swing.GroupLayout panel_eliminarLayout = new javax.swing.GroupLayout(panel_eliminar);
        panel_eliminar.setLayout(panel_eliminarLayout);
        panel_eliminarLayout.setHorizontalGroup(
            panel_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_eliminarLayout.setVerticalGroup(
            panel_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tab_administracion.addTab("eliminar", panel_eliminar);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Tabla de reportes");

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Edad", "ID", "ID de loteria"
            }
        ));
        jScrollPane1.setViewportView(tabla1);

        jLabel10.setText("Personas");

        cb_personas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_personasItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panel_reportesLayout = new javax.swing.GroupLayout(panel_reportes);
        panel_reportes.setLayout(panel_reportesLayout);
        panel_reportesLayout.setHorizontalGroup(
            panel_reportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_reportesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_reportesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panel_reportesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_personas, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_reportesLayout.setVerticalGroup(
            panel_reportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_reportesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(panel_reportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cb_personas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab_administracion.addTab("reportes", panel_reportes);

        tf_nuevonombre.setText("Nuevo nombre");

        jLabel12.setText("Nueva edad");

        jLabel11.setText("ID");

        jLabel13.setText("ID boleto");

        jLabel14.setText("Departamento");

        jLabel15.setText("Carrera");

        javax.swing.GroupLayout panel_alumno1Layout = new javax.swing.GroupLayout(panel_alumno1);
        panel_alumno1.setLayout(panel_alumno1Layout);
        panel_alumno1Layout.setHorizontalGroup(
            panel_alumno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_alumno1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tf_carrera1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_alumno1Layout.setVerticalGroup(
            panel_alumno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_alumno1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panel_alumno1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_carrera1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab_persona1.addTab("alumno", panel_alumno1);

        cb_partido1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nacional", "Liberal", "Pac", "Resistencia" }));

        javax.swing.GroupLayout panel_politico1Layout = new javax.swing.GroupLayout(panel_politico1);
        panel_politico1.setLayout(panel_politico1Layout);
        panel_politico1Layout.setHorizontalGroup(
            panel_politico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_politico1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(cb_partido1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_politico1Layout.setVerticalGroup(
            panel_politico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_politico1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(cb_partido1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab_persona1.addTab("politico", panel_politico1);

        jLabel16.setText("Ingrese su empleo");

        javax.swing.GroupLayout empleado1Layout = new javax.swing.GroupLayout(empleado1);
        empleado1.setLayout(empleado1Layout);
        empleado1Layout.setHorizontalGroup(
            empleado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empleado1Layout.createSequentialGroup()
                .addGroup(empleado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(empleado1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel16))
                    .addGroup(empleado1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(tf_empleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        empleado1Layout.setVerticalGroup(
            empleado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empleado1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(tf_empleado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab_persona1.addTab("empleado", empleado1);

        jLabel17.setText("Dinero");

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout panel_modificarLayout = new javax.swing.GroupLayout(panel_modificar);
        panel_modificar.setLayout(panel_modificarLayout);
        panel_modificarLayout.setHorizontalGroup(
            panel_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_modificarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(panel_modificarLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addComponent(jLabel17)
                    .addGroup(panel_modificarLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel12))
                    .addComponent(tf_nuevonombre, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab_persona1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_modificarLayout.setVerticalGroup(
            panel_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_modificarLayout.createSequentialGroup()
                .addGroup(panel_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_modificarLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(tab_persona1))
                    .addGroup(panel_modificarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tf_nuevonombre, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_modificarLayout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(25, 25, 25)
                        .addGroup(panel_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(141, 141, 141))
        );

        tab_administracion.addTab("Modificar", panel_modificar);

        javax.swing.GroupLayout panel_adiministracionLayout = new javax.swing.GroupLayout(panel_adiministracion);
        panel_adiministracion.setLayout(panel_adiministracionLayout);
        panel_adiministracionLayout.setHorizontalGroup(
            panel_adiministracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_adiministracionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab_administracion)
                .addContainerGap())
        );
        panel_adiministracionLayout.setVerticalGroup(
            panel_adiministracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_adiministracionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab_administracion, javax.swing.GroupLayout.PREFERRED_SIZE, 523, Short.MAX_VALUE)
                .addContainerGap())
        );

        tab_principal.addTab("adiministracion", panel_adiministracion);

        javax.swing.GroupLayout panel_ventasLayout = new javax.swing.GroupLayout(panel_ventas);
        panel_ventas.setLayout(panel_ventasLayout);
        panel_ventasLayout.setHorizontalGroup(
            panel_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
        );
        panel_ventasLayout.setVerticalGroup(
            panel_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
        );

        tab_principal.addTab("Ventas", panel_ventas);

        javax.swing.GroupLayout panel_rifasLayout = new javax.swing.GroupLayout(panel_rifas);
        panel_rifas.setLayout(panel_rifasLayout);
        panel_rifasLayout.setHorizontalGroup(
            panel_rifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
        );
        panel_rifasLayout.setVerticalGroup(
            panel_rifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
        );

        tab_principal.addTab("Rifas", panel_rifas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab_principal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_principal, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nombreActionPerformed

    private void tf_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_idActionPerformed

    private void tf_dineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_dineroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_dineroActionPerformed

    private void boton_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_guardarMouseClicked
        String nombre;
        int edad;
        String ID;
        String ID_loteria;
        String departamento;
        int dinero;
        try {
            edad = Integer.parseInt(tf_edad.getText());
            dinero = Integer.parseInt(tf_dinero.getText());
            nombre = tf_nombre.getText();
            ID = tf_id.getText();
            ID_loteria = tf_boleto.getText();
            departamento = cb_departamento.getSelectedItem().toString();
            if (tab_persona.getSelectedIndex() == 0) {
                String carrera = tf_carrera.getText();
                lista.add(new estudiantes(carrera, nombre, edad, ID, ID_loteria, departamento, dinero));
                JOptionPane.showMessageDialog(this, "Se guardo con exito");
                estudiantes p = new estudiantes(carrera, nombre, edad, ID, ID_loteria, departamento, dinero);
                cb_personas.addItem(p);
            } else if (tab_persona.getSelectedIndex() == 1) {
                String partido = cb_partido.getSelectedItem().toString();
                lista.add(new politico(partido, nombre, edad, ID, ID_loteria, departamento, dinero));
                JOptionPane.showMessageDialog(this, "Se guardo con exito");
                politico p = new politico(partido, nombre, edad, ID, ID_loteria, departamento, dinero);
                cb_personas.addItem(p);
            } else if (tab_persona.getSelectedIndex() == 2) {
                String empleado = tf_empleado.getText();
                lista.add(new empleados(empleado, nombre, edad, ID, ID_loteria, departamento, dinero));
                JOptionPane.showMessageDialog(this, "Se guardo con exito");
                empleados p = new empleados(empleado, nombre, edad, ID, ID_loteria, departamento, dinero);
                cb_personas.addItem(p);
            } 
            //resetear
            tf_nombre.setText("");
            tf_edad.setText("");
            tf_boleto.setText("");
            cb_departamento.setSelectedIndex(0);
            tf_dinero.setText("");
            tf_id.setText("");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocurrio un error y no se guardaron los datos");

        }
    }//GEN-LAST:event_boton_guardarMouseClicked

    private void cb_personasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_personasItemStateChanged
        if (evt.getStateChange() == 2) {
            persona s
                    = (persona) cb_personas.getSelectedItem();
            Object[] newrow = {
                s.getNombre(),
                s.getEdad(),
                s.getID(),
                s.getID_loteria()
            };
            DefaultTableModel modelo
                    = (DefaultTableModel) tabla1.getModel();
            modelo.addRow(newrow);
            tabla1.setModel(modelo);

        }
    }//GEN-LAST:event_cb_personasItemStateChanged

    private void tab_principalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tab_principalStateChanged
        if (tab_principal.getSelectedIndex() == 1) {
            DefaultComboBoxModel modelo
                    = new DefaultComboBoxModel();
            for (persona t : lista) {
                modelo.addElement(t);
            }
            cb_personas.setModel(modelo);
        }
    }//GEN-LAST:event_tab_principalStateChanged

    private void tf_edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_edadActionPerformed

    private void tab_administracionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tab_administracionStateChanged
       
    }//GEN-LAST:event_tab_administracionStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_guardar;
    private javax.swing.JComboBox<String> cb_departamento;
    private javax.swing.JComboBox<String> cb_partido;
    private javax.swing.JComboBox<String> cb_partido1;
    private javax.swing.JComboBox cb_personas;
    private javax.swing.JPanel empleado;
    private javax.swing.JPanel empleado1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel panel_adiministracion;
    private javax.swing.JPanel panel_agregar;
    private javax.swing.JPanel panel_alumno;
    private javax.swing.JPanel panel_alumno1;
    private javax.swing.JPanel panel_eliminar;
    private javax.swing.JPanel panel_modificar;
    private javax.swing.JPanel panel_politico;
    private javax.swing.JPanel panel_politico1;
    private javax.swing.JPanel panel_reportes;
    private javax.swing.JPanel panel_rifas;
    private javax.swing.JPanel panel_ventas;
    private javax.swing.JTabbedPane tab_administracion;
    private javax.swing.JTabbedPane tab_persona;
    private javax.swing.JTabbedPane tab_persona1;
    private javax.swing.JTabbedPane tab_principal;
    private javax.swing.JTable tabla1;
    private javax.swing.JTextField tf_boleto;
    private javax.swing.JTextField tf_carrera;
    private javax.swing.JTextField tf_carrera1;
    private javax.swing.JTextField tf_dinero;
    private javax.swing.JTextField tf_edad;
    private javax.swing.JTextField tf_empleado;
    private javax.swing.JTextField tf_empleado1;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JLabel tf_nuevonombre;
    // End of variables declaration//GEN-END:variables
ArrayList<persona> lista = new ArrayList();
}
